language: node_js
node_js:
- '0.10'
install:
- npm install -g demeteorizer
- demeteorizer
- cd ./.demeteorized
- 'echo "web: node main" > Procfile'
- npm install
- zip -r libreboard-cf ./*
deploy:
  provider: releases
  api_key:
    secure: sU47/RsQBBoGbezeuQYZzqQDw9MR6GVzqU49UeeTUfDTTbLsTS7PGAzDJCUOYBLl8QR48UpZiROFsx0uIUe6krqpFbR2xmyeSo+wFUMb7cD3+SSyup8Z6t7hEHYFcecsl3fWH9Ws35jpbMXaeMUd0CGZkaugPHB5isrzYSKtPcA=
  file: libreboard-cf.zip
  on:
    tags: true
    all_branches: true
